/**
 * 
 */
package org.eclipse.uide.editor;

/**
 * Interface to act as recipient for error messages generated by a parser/compiler during
 * "eager compilation". Used by the UniversalEditor to post annotations in the source editor.
 * @author rfuhrer
 */
public interface IMessageHandler {
    void handleMessage(int offset, int length, String message);
}